version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081

    depends_on:
      - mongo