version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081

    depends_on:
      - mongo

  java-api:
    image: java-aml-solo-api
    ports:
      - 8080:8080
    environment:
        SPRING_PROFILES_ACTIVE: prod
        DB_HOST: mongo
        DB_PORT: 27017
        DB_NAME: db-prod
    depends_on:
      - mongo