version: '2'

services:
    mongo:
#      container_name: mongo
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - /data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: the_password

    mongo-express:
#      container_name: mongo-express
      image: mongo-express:latest
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: the_password
#        ME_CONFIG_MONGODB_AUTH_USERNAME: user
#        ME_CONFIG_MONGODB_AUTH_PASSWORD: other_password
#        ME_CONFIG_MONGODB_SERVER: mongo

      depends_on:
        - mongo

#    java-app:
#      build: .
#      ports:
#        - 8080:8080
#      depends_on:
#        - mongo