# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker Push JAR upload

on:
  push:
    branches: [ docker-and-jar ]
  pull_request:
    branches: [ docker-and-jar ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Build Jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name:  Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERUSER }}/my-first-app:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar
